[build]
  command = "npm install && npm run build"
  publish = "src/dist"

[build.environment]
  NODE_VERSION = "18"
  DISABLE_PIP_INSTALL = "true"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "https://ai-dev-federation-dashboard.onrender.com/:splat"
  status = 200
  force = true
