[build]
  base = "src"
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://ai-dev-federation-dashboard.onrender.com/:splat"
  status = 200
  force = true