[build]
  base = ""
  command = "npm install && npm run build --prefix src"
  publish = "src/dist"

# Prevent Netlify from auto-detecting Python and installing requirements.txt
[build.environment]
  NODE_VERSION = "18"
  DISABLE_PIP_INSTALL = "true"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "https://ai-dev-federation-dashboard.onrender.com/:splat"
  status = 200
  force = true
