[build]
  # Run install at repo root, then build inside src/
  command = "npm install && npm run build --prefix src"
  # Publish the dist folder created inside src/
  publish = "src/dist"

[[redirects]]
  from = "/api/*"
  to = "https://ai-dev-federation-dashboard.onrender.com/:splat"
  status = 200
  force = true
