[build]
  command = "npm install && npm run build --prefix src"
  publish = "src/dist"

[build.environment]
  # Forces Netlify to skip Python detection
  PYTHON_VERSION = ""

[[redirects]]
  from = "/api/*"
  to = "https://ai-dev-federation-dashboard.onrender.com/:splat"
  status = 200
  force = true
