[build]
  base = "src"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://ai-dev-federation-dashboard.onrender.com/:splat"
  status = 200
  force = true
