services:
  - type: web
    name: ai-dev-federation-backend
    env: docker
    plan: free
    dockerContext: .              # build from repo root
    dockerfilePath: ./Dockerfile  # Dockerfile at repo root
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-dev-federation-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: HF_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "http://localhost:5173,https://aidevfederationdashboard.netlify.app"
      - key: PORT
        value: "8080"   # ✅ uvicorn binds to Render’s expected port
    healthCheckPath: /healthz
    autoDeploy: true

databases:
  - name: ai-dev-federation-db
    plan: free
