endpoints:
  - /health/ping
  - /healthz
  - /tasks/run/{preset}
  - /tasks/{task_id}
  - /tasks/{task_id}/stream
  - /repo/tree
  - /repo/file
  - /repo/file/structure
  - /repo/history
  - /repo/sha
  - /introspect/tables
  - /hf/stream
