endpoints:
  - /health/ping
  - /healthz                # ✅ needed for validate.ps1
  - /tasks/run
  - /tasks/{task_id}
  - /tasks/{task_id}/stream
  - /repo/tree
  - /repo/file
  - /repo/file/structure
  - /repo/history
  - /repo/sha
  - /introspect/tables
